#!/usr/bin/env python3
print("\nWar. War never changes.\n")
print("Most wars are fought for the same reasons. Money. Power. Revenge. Even love.  All of them. Every. Single. One. Driven by selfishness or pride. Such is the way of man. But this... this one is different. This is a fight for man\'s very survival. So we may survive to let kings and monarchs send \"lesser\" men to fight their petty squabbles for them.\n")
print("We\'ve been fighting the Dark Lord\'s forces for sometime.  Our army is strong. We were trained to fight demons as well as knights. We\'ve managed to push our forces up to his castle gates, and have made camp for the night. Hopefully, we can get some rest for the upcoming battle.\n")
print("You awaken to the sound of the commander shouting \"Get off your lazy arses! Sharpen your blades and suit up! We muster in 30!\" This gives me just enough time to put on my armor and eat breakfast, knowing full well it may be your last meal.\n")
print("HOW TO PLAY:")
print("Your objective is to navigate through the Dark Lord\'s castle, do battle with his minions, and slay the foul demon once and for all so peace can be restored to the land once more.")
print("----------------------------------")
print('Map Actions:\n')
print('    GO  [North, South, East, West, Up, Down]')
print('    GET [Item]')
print('    USE [Item, Spell]')
print('    LOOK')
print('    INVENTORY/INV')
print('    GEAR')
print('    EQUIP')
print('    STATUS/STATS')
print('    MENU\n')
print('    HELP\n')
print('    QUIT\n')
print('\n**Now that you\'re up, try using the \'LOOK\' command to check your surrounding environment. Maybe You\'ll find something useful?')
print('\nThen try using the \'GET\' command to grab anything tha looks useful. You can see the items you\'re holding with the \'INVENTORY\' or \'INV\' command.')
print('\nFinally, you can use the items with the \'USE\' command.')
print('\n**If you need a reminder on how to use any commands, type \'help\' at any time.**')
print('\n**Be aware, once you leave the tent, THERE\'S NO COMING BACK!**')
